### PR TITLE
Revised Metric: Event Demographics changes

### PR DESCRIPTION
**Pull request by TejasMate**
Issues solved:
Description included Attendee, Speaker, and Volunteer
4th point in the Objectives is redundant
Check out the spreadsheet remark
Added Last Reviewed date

Issue: #432

### CODE REVIEW

**Comment by germonprez** [comment]
Thanks for these @TejasMate - we will take a look at that in this week's DEI meeting

**Review by ElizabethN — CHANGES_REQUESTED** [review]
@TejasMate With regard to the 3rd bullet point on the list of 4 changes, could you add a sentence in the ## Description Section that says "This metric applies to both virtual and in-person events." (That was what @germonprez meant by the "spreadsheet remark".) Thanks!

**Comment by germonprez** [comment]
@ElizabethN - what do you think about merging this and then you could make a second PR with your suggested changes?

**Comment by ElizabethN** [comment]
@germonprez I can do that - no worries. Thanks for the PR @TejasMate! Merging now. 🙌

**Pull request merged**
