### PR TITLE
Update Copyright Year & Remove reference line of sample template

### PR DESCRIPTION
**Pull request by TejasMate**
1. Change Copyright year
2. Remove line "Blog posts, websites, academic papers, or books that mention the metric and provide more background." from **references**

### CODE REVIEW

**Comment by germonprez** [comment]
Thanks for taking a look at these @TejasMate -- we'll review in this week's DEI meeting

**Comment by TejasMate** [comment]
Sorry @germonprez, I want to commit for #431 issue mistakenly use same branch :(

**Comment by germonprez** [comment]
Thanks @TejasMate. Could you break this out in to 3-4 different PRs -- one per document change?

**Comment by TejasMate** [comment]
Yeah, sure. I will follow these while PRs

**Comment by germonprez** [comment]
Closing without merging. We have captured the recommendations for each of the respective documents. We will issue PRs against the single documents where appropriate. Thanks!

**Pull request closed without merging**
