### PR TITLE
Adding Equity and Trust Metric (starter)

### PR DESCRIPTION
**Pull request by emmairwin**
Added equity-trust as a metric under governance, as emerging knowledgeis that this is foundational for evaluating the impact of inclusive governance overall.

It's also something we will need for sustainability metrics model.

### CODE REVIEW

**Comment by germonprez** [comment]
Thanks @emmairwin! 

I've added this metric as an in-progress metric in the spreadsheet: 
https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit#gid=0

Also, I've copied this text over to a Google doc so we can work on it there: 
https://docs.google.com/document/d/1UHbnOaCoOmsdnf_xXHVmYDh3oDAI71_ugv4uzwhN38M/edit?usp=sharing

**Comment by germonprez** [comment]
We do generally (all the time) work on metrics in a shared doc first, before issuing a PR. We found this to be much easier for managing workflow in getting metrics published. It's totally fine to not use Google docs. Any shared document can work.

**Comment by emmairwin** [comment]
its fine, can go with the doc!  Not looking to change anything, was just curious.

**Comment by lucasgonze** [comment]
Regarding Google Docs, I think it's valuable to take note of contexts in which they are suboptimal. I can think of three:

1. In China and other countries where Docs is disallowed
2. When free software partisans prefer open formats such as markdown or LibreOffice
3. When participants work for Google competitors

**Comment by ElizabethN** [comment]
We reviewed this in the DEI working group and decided it's ok to close, since this work is captured in our normal workflow. A new PR will get merged when the metric is complete and ready for release. :+1: Thanks @emmairwin!

**Pull request closed without merging**
